### ISSUE TITLE
Failure to run cargo

### ISSUE THREAD

**Issue by LordPython** [PistonDevelopers/VisualRust#249]
Using the latest build on AppVeyor (140), whenever I try to build a rust solution (just the empty application or library template), I get the following error:

```
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018: The "CargoBuild" task failed unexpectedly.
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018: System.InvalidOperationException: StandardErrorEncoding is only supported when standard error is redirected.
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at System.Diagnostics.Process.Start()
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at VisualRust.Shared.Cargo.GetCargoVersion(String exePath)
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at VisualRust.Shared.Cargo.<>c.<FindSupportedInstallation>b__12_1(String p)
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at VisualRust.Shared.Cargo.FindSupportedInstallation()
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at VisualRust.Build.CargoTask.Execute()
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(62,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by Vbif** [comment]
Ooops. That my error. Please try 139 build from AppVeyor

**Comment by LordPython** [comment]
Yes, I had just tried that, and it seems to be working.
