### ISSUE TITLE
Extension installation fails on VS 2017

### ISSUE THREAD

**Issue by Liano** [PistonDevelopers/VisualRust#285]
I tried to install the last version on VS 2K17 community on windows 7 x64 but fail during extension installation
the following is install log

> 	10/06/2017 22:20:59 - Microsoft VSIX Installer
	10/06/2017 22:20:59 - -------------------------------------------
	10/06/2017 22:20:59 - vsixinstaller.exe version:
	10/06/2017 22:20:59 - 15.0.26209.1 built by: D15REL
	10/06/2017 22:20:59 - -------------------------------------------
	10/06/2017 22:20:59 - Command line parameters:
	10/06/2017 22:20:59 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,/admin,/logFile:C:\Users\najib\AppData\Local\Temp\Visual_Rust_for_Visual_Studio_2017_20170610222050_002_VSIXBootstrapper.log,C:\ProgramData\Package Cache\9864EE5369359DB622D0234B6C6B7640B949140C\VisualRust.vsix
	10/06/2017 22:20:59 - -------------------------------------------
	10/06/2017 22:20:59 - Microsoft VSIX Installer
	10/06/2017 22:20:59 - -------------------------------------------
	10/06/2017 22:21:00 - Initializing Install...
	10/06/2017 22:21:02 - Extension Details...
	10/06/2017 22:21:02 - 	Identifier         : 40c1d2b5-528b-4966-a7b1-1974e3568abe
	10/06/2017 22:21:02 - 	Name               : Visual Rust
	10/06/2017 22:21:02 - 	Author             : The Piston Project
	10/06/2017 22:21:02 - 	Version            : 0.2.0
	10/06/2017 22:21:02 - 	Description        : Visual Studio integration for the Rust programming language (http://www.rust-lang.org/)
	10/06/2017 22:21:02 - 	Locale             : en-US
	10/06/2017 22:21:02 - 	MoreInfoURL        : 
	10/06/2017 22:21:02 - 	InstalledByMSI     : False
	10/06/2017 22:21:02 - 	SupportedFrameworkVersionRange : [4.6,)
	10/06/2017 22:21:02 - 
	10/06/2017 22:21:02 - 	SignatureState     : Unsigned
	10/06/2017 22:21:02 - 	Supported Products : 
	10/06/2017 22:21:02 - 		Microsoft.VisualStudio.Community
	10/06/2017 22:21:02 - 			Version : [15.0,)
	10/06/2017 22:21:02 - 		Microsoft.VisualStudio.Pro
	10/06/2017 22:21:02 - 			Version : [15.0,)
	10/06/2017 22:21:02 - 		Microsoft.VisualStudio.Enterprise
	10/06/2017 22:21:02 - 			Version : [15.0,)
	10/06/2017 22:21:02 - 
	10/06/2017 22:21:02 - 	References         : 
	10/06/2017 22:21:02 - 	Prerequisites      : 
	10/06/2017 22:21:02 - 		-------------------------------------------------------
	10/06/2017 22:21:02 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
	10/06/2017 22:21:02 - 		Name         : Visual Studio core editor
	10/06/2017 22:21:02 - 		Version      : [15.0,)
	10/06/2017 22:21:02 - 
	10/06/2017 22:21:02 - 		-------------------------------------------------------
	10/06/2017 22:21:02 - 		Identifier   : Microsoft.VisualStudio.Component.VC.CoreIde
	10/06/2017 22:21:02 - 		Name         : Visual Studio C++ core features
	10/06/2017 22:21:02 - 		Version      : [15.0,16.0)
	10/06/2017 22:21:02 - 
	10/06/2017 22:21:02 - Signature Details...
	10/06/2017 22:21:02 - 	Extension is not signed.
	10/06/2017 22:21:02 - 
	10/06/2017 22:21:02 - Searching for applicable products...
	10/06/2017 22:21:02 - Found installed product - Global Location
	10/06/2017 22:21:02 - Found installed product - Visual Studio Build Tools 2017 (2)
	10/06/2017 22:21:02 - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
	   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
	   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
	   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
	   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
	   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
	   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
	   at VSIXInstaller.App.Initialize()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()

this happened on the last version currently available.

**Comment by MaulingMonkey** [comment]
At first glance this looks more like it has something to do with a bad/deleted/missing install of "Visual Studio Build Tools 2017" than Visual Rust.  I don't currently have VS2017 installed to test myself however...
