### ISSUE TITLE
VS 2017 - latest from CI NRE

### ISSUE THREAD

**Issue by clairernovotny** [PistonDevelopers/VisualRust#299]
With the latest AppVeyor version for 2017, I'm getting exceptions on build

```
=====================
7/29/2017 2:11:35 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at VisualRust.Build.Rustc.LogRustcMessage(RustcMessageJson msg, String rootPath, TaskLoggingHelper log)
   at VisualRust.Build.CargoBuild.<ExecuteCargo>b__4_1(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
===================
```

**Comment by Boddlnagg** [comment]
Probably a duplicate of #296 ?

**Comment by clairernovotny** [comment]
Appears to be the same issue. Is there a later build that has that fix in it?

**Comment by MaulingMonkey** [comment]
There is a build of my unofficial, pending review pull request:

https://ci.appveyor.com/project/MaulingMonkey/visualrust/build/job/bgfigmcko2211nin/artifacts

If you do want to try it out, you'll want to uninstall the previous version (twice! via Visual Studio's "Extensions and Updates", and then via Windows's "Programs and Features") before installing mine.

**Comment by clairernovotny** [comment]
@MaulingMonkey will take a look at your version. @Boddlnagg is there a plan to review/merge that back in to the official version? I see it's been a while since there has been a VS Marketplace update too; is there something that can be done to help?

**Comment by Boddlnagg** [comment]
Yes, this should definitely be merged back into the official version, but I'm hesitant to merge such large changes without having @vosen take a look at it, who officially maintains this project ... and I also don't really have time to review them in detail at the moment.

Testing the PR and reporting any issues is probably something that would help 😄

**Comment by MaulingMonkey** [comment]
And as the proverbial raging bull in a china shop, I agree it could use a review.  I don't even know rust!  ;)

**Comment by clairernovotny** [comment]
I'm just learning Rust now...and my tool of choice is VS, so this definitely helps make it easier. What I do know is MSBuild pretty well... I have not really tried to implement a project system though. I'll install @MaulingMonkey's version now.
