### ISSUE TITLE
visualrust with vs2017 doesn't seem to work

### ISSUE THREAD

**Issue by ellisonch** [PistonDevelopers/VisualRust#307]
I'm using visual studio community 2017 (15.6.3) and I'd like to use Visual Rust with it.  I installed the `bin\VisualRust.Setup.2017\Release\VisualRust.Setup.2017.exe` artifact (dated December 4th, 2017) from https://ci.appveyor.com/project/vosen/visualrust/build/artifacts (I couldn't find any other version for VS2017.  It installed just fine with no errors.  When I started VS back up, I don't see anything different---no new templates or project types or anything.  VS2017 does think it's installed (based on going to tools/extensions), it just doesn't seem to do anything.  If I go to add new project or add new file and look/search for rust, nothing.

However, if I open a .rs file in VS, it does syntax highlight it, but "go to definition" doesn't work, and I can't build.

**Comment by GLeBaTi** [comment]
![image](https://user-images.githubusercontent.com/693132/41145075-9428c5bc-6b07-11e8-8495-f13ed6bc8a11.png)
I have not rsproj too

**Comment by glebov21** [comment]
Installing from this: ( https://ci.appveyor.com/project/MaulingMonkey/visualrust/build/8 ) solve my problem. (click "Configuration: Release" -> Artifacts -> VisualRust.Setup.2017.exe)
Uninstall previous version (put LICENSE.txt if needed to ide folder)

But i have now when buid project: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at VisualRust.Build.Rustc.LogRustcMessage(RustcMessageJson msg, String rootPath, TaskLoggingHelper log)
   at VisualRust.Build.CargoBuild.<ExecuteCargo>b__4_1(Object sender, DataReceivedEventArgs e)
```

**Comment by sgeos** [comment]
The above artifact seems to have been deleted due to age.  Is there another place from which an artifact can be downloaded?
